# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('update_time', models.DateTimeField()),
            ],
        ),
    ]
